# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpwbart <- function(sexp_itress, sexp_ix, sexp_itc) {
    .Call(`_BartVS_cpwbart`, sexp_itress, sexp_ix, sexp_itc)
}

cwbart_two_step <- function(sexp_in, sexp_ip, sexp_inp, sexp_ix, sexp_iy, sexp_ixp, sexp_im, sexp_inc, sexp_ind, sexp_iburn, sexp_ipower, sexp_ibase, sexp_itau, sexp_inu, sexp_ilambda, sexp_isigest, sexp_iw, sexp_idart, sexp_itheta, sexp_iomega, sexp_igrp, sexp_ia, sexp_ib, sexp_irho, sexp_iaug, sexp_inkeeptrain, sexp_inkeeptest, sexp_inkeeptestme, sexp_inkeeptreedraws, sexp_inprintevery, sexp_Xinfo, sexp_Z, sexp_q, sexp_group_num, sexp_id, sexp_z_b, sexp_z_lambda, sexp_z_lambda_mean, sexp_z_lambda_cov, sexp_z_alpha, sexp_z_beta, sexp_seed) {
    .Call(`_BartVS_cwbart_two_step`, sexp_in, sexp_ip, sexp_inp, sexp_ix, sexp_iy, sexp_ixp, sexp_im, sexp_inc, sexp_ind, sexp_iburn, sexp_ipower, sexp_ibase, sexp_itau, sexp_inu, sexp_ilambda, sexp_isigest, sexp_iw, sexp_idart, sexp_itheta, sexp_iomega, sexp_igrp, sexp_ia, sexp_ib, sexp_irho, sexp_iaug, sexp_inkeeptrain, sexp_inkeeptest, sexp_inkeeptestme, sexp_inkeeptreedraws, sexp_inprintevery, sexp_Xinfo, sexp_Z, sexp_q, sexp_group_num, sexp_id, sexp_z_b, sexp_z_lambda, sexp_z_lambda_mean, sexp_z_lambda_cov, sexp_z_alpha, sexp_z_beta, sexp_seed)
}

cwbart_unified <- function(sexp_in, sexp_ip, sexp_inp, sexp_ix, sexp_iy, sexp_ixp, sexp_im, sexp_inc, sexp_ind, sexp_iburn, sexp_ipower, sexp_ibase, sexp_itau, sexp_inu, sexp_ilambda, sexp_isigest, sexp_iw, sexp_idart, sexp_itheta, sexp_iomega, sexp_igrp, sexp_ia, sexp_ib, sexp_irho, sexp_iaug, sexp_inkeeptrain, sexp_inkeeptest, sexp_inkeeptestme, sexp_inkeeptreedraws, sexp_inprintevery, sexp_Xinfo, sexp_Z, sexp_q, sexp_group_num, sexp_id, sexp_z_b, sexp_z_gamma, sexp_z_gamma_mean, sexp_z_gamma_cov, sexp_z_lambda, sexp_z_lambda_mean, sexp_z_lambda_cov, sexp_z_alpha, sexp_z_beta, sexp_seed) {
    .Call(`_BartVS_cwbart_unified`, sexp_in, sexp_ip, sexp_inp, sexp_ix, sexp_iy, sexp_ixp, sexp_im, sexp_inc, sexp_ind, sexp_iburn, sexp_ipower, sexp_ibase, sexp_itau, sexp_inu, sexp_ilambda, sexp_isigest, sexp_iw, sexp_idart, sexp_itheta, sexp_iomega, sexp_igrp, sexp_ia, sexp_ib, sexp_irho, sexp_iaug, sexp_inkeeptrain, sexp_inkeeptest, sexp_inkeeptestme, sexp_inkeeptreedraws, sexp_inprintevery, sexp_Xinfo, sexp_Z, sexp_q, sexp_group_num, sexp_id, sexp_z_b, sexp_z_gamma, sexp_z_gamma_mean, sexp_z_gamma_cov, sexp_z_lambda, sexp_z_lambda_mean, sexp_z_lambda_cov, sexp_z_alpha, sexp_z_beta, sexp_seed)
}

