// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpwbart
RcppExport SEXP cpwbart(SEXP sexp_itress, SEXP sexp_ix, SEXP sexp_itc);
RcppExport SEXP _BartRI_cpwbart(SEXP sexp_itressSEXP, SEXP sexp_ixSEXP, SEXP sexp_itcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_itress(sexp_itressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ix(sexp_ixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_itc(sexp_itcSEXP);
    rcpp_result_gen = Rcpp::wrap(cpwbart(sexp_itress, sexp_ix, sexp_itc));
    return rcpp_result_gen;
END_RCPP
}
// cwbart
RcppExport SEXP cwbart(SEXP sexp_in, SEXP sexp_ip, SEXP sexp_inp, SEXP sexp_ix, SEXP sexp_iy, SEXP sexp_ixp, SEXP sexp_im, SEXP sexp_inc, SEXP sexp_ind, SEXP sexp_iburn, SEXP sexp_ipower, SEXP sexp_ibase, SEXP sexp_itau, SEXP sexp_inu, SEXP sexp_ilambda, SEXP sexp_isigest, SEXP sexp_iw, SEXP sexp_idart, SEXP sexp_itheta, SEXP sexp_iomega, SEXP sexp_igrp, SEXP sexp_ia, SEXP sexp_ib, SEXP sexp_irho, SEXP sexp_iaug, SEXP sexp_inkeeptrain, SEXP sexp_inkeeptest, SEXP sexp_inkeeptestme, SEXP sexp_inkeeptreedraws, SEXP sexp_inprintevery, SEXP sexp_Xinfo, SEXP sexp_Z, SEXP sexp_q, SEXP sexp_group_num, SEXP sexp_id, SEXP sexp_z_c0, SEXP sexp_z_d0, SEXP sexp_z_b, SEXP sexp_z_gamma, SEXP sexp_z_gamma_mean, SEXP sexp_z_gamma_cov, SEXP sexp_z_lambda, SEXP sexp_z_lambda_mean, SEXP sexp_z_lambda_cov, SEXP sexp_z_alpha, SEXP sexp_z_beta, SEXP sexp_seed);
RcppExport SEXP _BartRI_cwbart(SEXP sexp_inSEXP, SEXP sexp_ipSEXP, SEXP sexp_inpSEXP, SEXP sexp_ixSEXP, SEXP sexp_iySEXP, SEXP sexp_ixpSEXP, SEXP sexp_imSEXP, SEXP sexp_incSEXP, SEXP sexp_indSEXP, SEXP sexp_iburnSEXP, SEXP sexp_ipowerSEXP, SEXP sexp_ibaseSEXP, SEXP sexp_itauSEXP, SEXP sexp_inuSEXP, SEXP sexp_ilambdaSEXP, SEXP sexp_isigestSEXP, SEXP sexp_iwSEXP, SEXP sexp_idartSEXP, SEXP sexp_ithetaSEXP, SEXP sexp_iomegaSEXP, SEXP sexp_igrpSEXP, SEXP sexp_iaSEXP, SEXP sexp_ibSEXP, SEXP sexp_irhoSEXP, SEXP sexp_iaugSEXP, SEXP sexp_inkeeptrainSEXP, SEXP sexp_inkeeptestSEXP, SEXP sexp_inkeeptestmeSEXP, SEXP sexp_inkeeptreedrawsSEXP, SEXP sexp_inprinteverySEXP, SEXP sexp_XinfoSEXP, SEXP sexp_ZSEXP, SEXP sexp_qSEXP, SEXP sexp_group_numSEXP, SEXP sexp_idSEXP, SEXP sexp_z_c0SEXP, SEXP sexp_z_d0SEXP, SEXP sexp_z_bSEXP, SEXP sexp_z_gammaSEXP, SEXP sexp_z_gamma_meanSEXP, SEXP sexp_z_gamma_covSEXP, SEXP sexp_z_lambdaSEXP, SEXP sexp_z_lambda_meanSEXP, SEXP sexp_z_lambda_covSEXP, SEXP sexp_z_alphaSEXP, SEXP sexp_z_betaSEXP, SEXP sexp_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_in(sexp_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ip(sexp_ipSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inp(sexp_inpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ix(sexp_ixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_iy(sexp_iySEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ixp(sexp_ixpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_im(sexp_imSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inc(sexp_incSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ind(sexp_indSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_iburn(sexp_iburnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ipower(sexp_ipowerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ibase(sexp_ibaseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_itau(sexp_itauSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inu(sexp_inuSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ilambda(sexp_ilambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_isigest(sexp_isigestSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_iw(sexp_iwSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_idart(sexp_idartSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_itheta(sexp_ithetaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_iomega(sexp_iomegaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_igrp(sexp_igrpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ia(sexp_iaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_ib(sexp_ibSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_irho(sexp_irhoSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_iaug(sexp_iaugSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inkeeptrain(sexp_inkeeptrainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inkeeptest(sexp_inkeeptestSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inkeeptestme(sexp_inkeeptestmeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inkeeptreedraws(sexp_inkeeptreedrawsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_inprintevery(sexp_inprinteverySEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_Xinfo(sexp_XinfoSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_Z(sexp_ZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_q(sexp_qSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_group_num(sexp_group_numSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_id(sexp_idSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_c0(sexp_z_c0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_d0(sexp_z_d0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_b(sexp_z_bSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_gamma(sexp_z_gammaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_gamma_mean(sexp_z_gamma_meanSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_gamma_cov(sexp_z_gamma_covSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_lambda(sexp_z_lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_lambda_mean(sexp_z_lambda_meanSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_lambda_cov(sexp_z_lambda_covSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_alpha(sexp_z_alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_z_beta(sexp_z_betaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sexp_seed(sexp_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cwbart(sexp_in, sexp_ip, sexp_inp, sexp_ix, sexp_iy, sexp_ixp, sexp_im, sexp_inc, sexp_ind, sexp_iburn, sexp_ipower, sexp_ibase, sexp_itau, sexp_inu, sexp_ilambda, sexp_isigest, sexp_iw, sexp_idart, sexp_itheta, sexp_iomega, sexp_igrp, sexp_ia, sexp_ib, sexp_irho, sexp_iaug, sexp_inkeeptrain, sexp_inkeeptest, sexp_inkeeptestme, sexp_inkeeptreedraws, sexp_inprintevery, sexp_Xinfo, sexp_Z, sexp_q, sexp_group_num, sexp_id, sexp_z_c0, sexp_z_d0, sexp_z_b, sexp_z_gamma, sexp_z_gamma_mean, sexp_z_gamma_cov, sexp_z_lambda, sexp_z_lambda_mean, sexp_z_lambda_cov, sexp_z_alpha, sexp_z_beta, sexp_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BartRI_cpwbart", (DL_FUNC) &_BartRI_cpwbart, 3},
    {"_BartRI_cwbart", (DL_FUNC) &_BartRI_cwbart, 47},
    {NULL, NULL, 0}
};

RcppExport void R_init_BartRI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
